"""Add Project Service models with RBAC and audit trail

Revision ID: 809aaed134f3
Revises: 4c055ac6469f
Create Date: 2025-11-11 13:00:51.111578

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "809aaed134f3"
down_revision = "4c055ac6469f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("consultation_date", sa.Date(), nullable=True),
        sa.Column("submission_deadline", sa.Date(), nullable=True),
        sa.Column("notification_date", sa.Date(), nullable=True),
        sa.Column("contract_start_date", sa.Date(), nullable=True),
        sa.Column("planned_start_date", sa.Date(), nullable=True),
        sa.Column("actual_start_date", sa.Date(), nullable=True),
        sa.Column("contract_delivery_date", sa.Date(), nullable=True),
        sa.Column("planned_delivery_date", sa.Date(), nullable=True),
        sa.Column("actual_delivery_date", sa.Date(), nullable=True),
        sa.Column(
            "contract_amount", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("budget_currency", sa.String(length=3), nullable=True),
        sa.Column("suspended_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('created', 'initialized', 'consultation', 'lost', 'active', 'suspended', 'completed', 'archived')",
            name="check_project_status",
        ),
        sa.CheckConstraint(
            "budget_currency IS NULL OR length(budget_currency) = 3",
            name="check_currency_code",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(
            "idx_projects_company_removed",
            ["company_id", "removed_at"],
            unique=False,
        )
        batch_op.create_index(
            "idx_projects_company_status",
            ["company_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            "idx_projects_customer", ["customer_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_projects_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_projects_status"), ["status"], unique=False
        )

    op.create_table(
        "deliverables",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("planned_date", sa.Date(), nullable=True),
        sa.Column("actual_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('planned', 'in_progress', 'completed', 'delayed', 'cancelled')",
            name="check_deliverable_status",
        ),
        sa.CheckConstraint(
            "type IN ('document', 'software', 'hardware', 'service', 'other')",
            name="check_deliverable_type",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deliverables", schema=None) as batch_op:
        batch_op.create_index(
            "idx_deliverables_company", ["company_id"], unique=False
        )
        batch_op.create_index(
            "idx_deliverables_project_status",
            ["project_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_deliverables_company_id"),
            ["company_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_deliverables_project_id"),
            ["project_id"],
            unique=False,
        )

    op.create_table(
        "milestones",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("planned_date", sa.Date(), nullable=True),
        sa.Column("actual_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('planned', 'in_progress', 'completed', 'delayed', 'cancelled')",
            name="check_milestone_status",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("milestones", schema=None) as batch_op:
        batch_op.create_index(
            "idx_milestones_company", ["company_id"], unique=False
        )
        batch_op.create_index(
            "idx_milestones_project_status",
            ["project_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_milestones_company_id"),
            ["company_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_milestones_project_id"),
            ["project_id"],
            unique=False,
        )

    op.create_table(
        "project_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("changed_by", sa.UUID(), nullable=False),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("field_name", sa.String(length=50), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "action IN ('created', 'updated', 'status_changed', 'deleted', 'restored', 'member_added', 'member_removed', 'role_assigned')",
            name="check_history_action",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_history", schema=None) as batch_op:
        batch_op.create_index(
            "idx_project_history_action", ["action"], unique=False
        )
        batch_op.create_index(
            "idx_project_history_company", ["company_id"], unique=False
        )
        batch_op.create_index(
            "idx_project_history_project_date",
            ["project_id", "changed_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_project_history_changed_at"),
            ["changed_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_project_history_company_id"),
            ["company_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_project_history_project_id"),
            ["project_id"],
            unique=False,
        )

    op.create_table(
        "project_permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "category IN ('file_operations', 'project_operations', 'member_operations')",
            name="check_permission_category",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "name", name="uq_project_permission_name"
        ),
    )
    with op.batch_alter_table("project_permissions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_project_permissions_category", ["category"], unique=False
        )
        batch_op.create_index(
            "idx_project_permissions_company", ["company_id"], unique=False
        )
        batch_op.create_index(
            "idx_project_permissions_project_name",
            ["project_id", "name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_project_permissions_company_id"),
            ["company_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_project_permissions_project_id"),
            ["project_id"],
            unique=False,
        )

    op.create_table(
        "project_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "name", name="uq_project_policy_name"
        ),
    )
    with op.batch_alter_table("project_policies", schema=None) as batch_op:
        batch_op.create_index(
            "idx_project_policies_company", ["company_id"], unique=False
        )
        batch_op.create_index(
            "idx_project_policies_project_name",
            ["project_id", "name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_project_policies_company_id"),
            ["company_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_project_policies_project_id"),
            ["project_id"],
            unique=False,
        )

    op.create_table(
        "project_roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_project_role_name"),
    )
    with op.batch_alter_table("project_roles", schema=None) as batch_op:
        batch_op.create_index(
            "idx_project_roles_company", ["company_id"], unique=False
        )
        batch_op.create_index(
            "idx_project_roles_project_name",
            ["project_id", "name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_project_roles_company_id"),
            ["company_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_project_roles_project_id"),
            ["project_id"],
            unique=False,
        )

    op.create_table(
        "milestone_deliverable_association",
        sa.Column("milestone_id", sa.UUID(), nullable=False),
        sa.Column("deliverable_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deliverable_id"], ["deliverables.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["milestone_id"], ["milestones.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("milestone_id", "deliverable_id"),
    )
    op.create_table(
        "policy_permission_association",
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["project_permissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"], ["project_policies.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("policy_id", "permission_id"),
    )
    op.create_table(
        "project_members",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.Column("added_by", sa.UUID(), nullable=False),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["project_roles.id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "user_id"),
    )
    with op.batch_alter_table("project_members", schema=None) as batch_op:
        batch_op.create_index(
            "idx_project_members_company", ["company_id"], unique=False
        )
        batch_op.create_index(
            "idx_project_members_role", ["role_id"], unique=False
        )
        batch_op.create_index(
            "idx_project_members_user", ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_project_members_company_id"),
            ["company_id"],
            unique=False,
        )

    op.create_table(
        "role_policy_association",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["policy_id"], ["project_policies.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["project_roles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("role_id", "policy_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role_policy_association")
    with op.batch_alter_table("project_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_members_company_id"))
        batch_op.drop_index("idx_project_members_user")
        batch_op.drop_index("idx_project_members_role")
        batch_op.drop_index("idx_project_members_company")

    op.drop_table("project_members")
    op.drop_table("policy_permission_association")
    op.drop_table("milestone_deliverable_association")
    with op.batch_alter_table("project_roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_roles_project_id"))
        batch_op.drop_index(batch_op.f("ix_project_roles_company_id"))
        batch_op.drop_index("idx_project_roles_project_name")
        batch_op.drop_index("idx_project_roles_company")

    op.drop_table("project_roles")
    with op.batch_alter_table("project_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_policies_project_id"))
        batch_op.drop_index(batch_op.f("ix_project_policies_company_id"))
        batch_op.drop_index("idx_project_policies_project_name")
        batch_op.drop_index("idx_project_policies_company")

    op.drop_table("project_policies")
    with op.batch_alter_table("project_permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_permissions_project_id"))
        batch_op.drop_index(batch_op.f("ix_project_permissions_company_id"))
        batch_op.drop_index("idx_project_permissions_project_name")
        batch_op.drop_index("idx_project_permissions_company")
        batch_op.drop_index("idx_project_permissions_category")

    op.drop_table("project_permissions")
    with op.batch_alter_table("project_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_history_project_id"))
        batch_op.drop_index(batch_op.f("ix_project_history_company_id"))
        batch_op.drop_index(batch_op.f("ix_project_history_changed_at"))
        batch_op.drop_index("idx_project_history_project_date")
        batch_op.drop_index("idx_project_history_company")
        batch_op.drop_index("idx_project_history_action")

    op.drop_table("project_history")
    with op.batch_alter_table("milestones", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_milestones_project_id"))
        batch_op.drop_index(batch_op.f("ix_milestones_company_id"))
        batch_op.drop_index("idx_milestones_project_status")
        batch_op.drop_index("idx_milestones_company")

    op.drop_table("milestones")
    with op.batch_alter_table("deliverables", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deliverables_project_id"))
        batch_op.drop_index(batch_op.f("ix_deliverables_company_id"))
        batch_op.drop_index("idx_deliverables_project_status")
        batch_op.drop_index("idx_deliverables_company")

    op.drop_table("deliverables")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_status"))
        batch_op.drop_index(batch_op.f("ix_projects_company_id"))
        batch_op.drop_index("idx_projects_customer")
        batch_op.drop_index("idx_projects_company_status")
        batch_op.drop_index("idx_projects_company_removed")

    op.drop_table("projects")
    # ### end Alembic commands ###
